### ISSUE TITLE
'SingleLayerUnsupervised' object has no attribute 'params'

### ISSUE THREAD

**Issue by saj1919** [wuaalb/keras_extensions#4] opened 2016-02-22 07:48 UTC
Hi, I am getting following error after running example.py

```
Using Theano backend.
Creating training model...
Compiling Theano graph...
Traceback (most recent call last):
  File "example.py", line 110, in <module>
    main()
  File "/data5/kmeans_doc2vec/rbm/ml_cf/keras_extensions-master/keras_extensions/logging.py", line 118, in wrapped
    original_func(*args, **kwargs)
  File "example.py", line 63, in main
    train_model.compile(optimizer=opt, loss=contastive_divergence)
  File "/data5/kmeans_doc2vec/rbm/ml_cf/keras_extensions-master/keras_extensions/models.py", line 35, in compile
    updates = self.optimizer.get_updates(self.params, self.constraints, train_loss)
AttributeError: 'SingleLayerUnsupervised' object has no attribute 'params'
```

**Comment by wuaalb** [comment] 2016-02-22 09:40
Hi,

The problem is that Keras is constantly changing and that this code is strongly coupled to Keras' internals.

So, you have two options
1. Modify the code so it works with latest Keras. To do so you should probably look at the class that generated the error, in this case `SingleLayerUnsupervised`, and check the comments that say which Keras class it is based on, in this case `keras.layers.containers.Sequential` and `keras.models.Sequential`. If you look at the differences between the latest Keras code for those classes and the derived code, it should be pretty straight forward to update it.
2. Use an older version of Keras, check when was the last commit to `keras_extensions` and get a version of Keras from around that date.

Personally I'm fine with using an older version of Keras for my RBM experiments, so I'm not very committed to keeping this up to date all the time.

**Comment by saj1919** [comment] 2016-02-22 09:49
Hey, Thanks for the reply. Which version are you using ? I will use the same one for time being instead of deep-diving into keras code.

**Comment by wuaalb** [comment] 2016-02-22 10:20
Maybe try Keras commit 80096798fc3ecbd51e8e7a9109d6344d808d03a7 (dec 18).

**Comment by Cospel** [comment] 2016-03-07 18:57
Try to change self.params to `self.trainable_weights`. It worked for me.

But now in the inference i get new error, can you help me? :)

```
Using gpu device 0: Quadro K620 (CNMeM is disabled)
Using Theano backend.
Creating training model...
Compiling Theano graph...
Training...
Epoch 1/10
Changed momentum to: 0.500
9000/9000 [==============================] - 1s - loss: 900.5594     
Epoch 2/10
9000/9000 [==============================] - 2s - loss: 899.1285     
Epoch 3/10
9000/9000 [==============================] - 2s - loss: 899.2937     
Epoch 4/10
9000/9000 [==============================] - 2s - loss: 898.9639     
Epoch 5/10
9000/9000 [==============================] - 2s - loss: 899.0473     
Epoch 6/10
Changed momentum to: 0.900
9000/9000 [==============================] - 2s - loss: 898.8275     
Epoch 7/10
9000/9000 [==============================] - 2s - loss: 899.5338     
Epoch 8/10
9000/9000 [==============================] - 2s - loss: 899.2616     
Epoch 9/10
9000/9000 [==============================] - 2s - loss: 898.7913     
Epoch 10/10
9000/9000 [==============================] - 2s - loss: 898.5857     
Training took 0.337594 minutes
Saving model...
Loading model...
Creating inference model...
Compiling Theano graph...
Traceback (most recent call last):
  File "example.py", line 114, in <module>
    main()
  File "/home/myuser/keras_extensions/keras_extensions/logging.py", line 118, in wrapped
    original_func(*args, **kwargs)
  File "example.py", line 104, in main
    inference_model.compile(opt, loss='mean_squared_error') # XXX: optimizer and loss are not used!
  File "/home/myuser/anaconda/lib/python2.7/site-packages/keras/models.py", line 467, in compile
    self.y_train = self.get_output(train=True)
  File "/home/myuser/anaconda/lib/python2.7/site-packages/keras/layers/containers.py", line 128, in get_output
    return self.layers[-1].get_output(train)
  File "/home/myuser/keras_extensions/keras_extensions/layers.py", line 23, in get_output
    p = self.get_input(train)
  File "/home/myuser/anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/myuser/anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 971, in get_output
    output = self.activation(K.dot(X, self.W) + self.b)
AttributeError: 'Dense' object has no attribute 'W'

```

**Comment by Cospel** [comment] 2016-03-07 19:15
It looks like when BernoulliLayer wants to get_input, it looks for the previous Dense layer but this has no W.

**Comment by wuaalb** [comment] 2016-03-07 19:18
The 'W' attribute is created in `Dense.build()`, so I guess that isn't called (not sure when/how it's supposed to be called in recent Keras).

**Closed** 2016-03-31 14:37 UTC
